// Generated by https://quicktype.io

import 'package:valua_staff/models/account.dart';
import 'package:json_annotation/json_annotation.dart';

part 'app_user.g.dart';

@JsonSerializable()
class AppUser {
  Account appUser;
  String token;

  AppUser({
    required this.appUser,
    required this.token,
  });

  factory AppUser.fromJson(Map<String, dynamic> json) =>
      _$AppUserFromJson(json);

  Map<String, dynamic> toJson() => _$AppUserToJson(this);
}
